### ISSUE TITLE
tree.children and tree.transitions in dpw

### ISSUE THREAD

**Issue by rcnlee** [JuliaPOMDP/MCTS.jl#35]
There seems to be a difference between the pseudocode in
https://arxiv.org/pdf/1405.5498.pdf
and the implementation in dpw.jl.  

In the paper, A(s) is a set, whereas in dpw.jl it is a vector (which allows repetitions).  So when checking whether to widen or not, the former checks unique elements whereas the latter checks total number of elements.  If the distribution is very peaked and you get a lot of repetitions, the first case will keep allowing to sample new actions, whereas the second will be constantly hitting the widening limit.

Maybe it doesn't matter so much, I'm not sure, but I'd like to hear your thoughts.

Thanks!

**Comment by rcnlee** [comment]
Maybe I'm confused.  You seem to have lookups to check for repeated actions so that the vector contains only unique actions.  But then here 
https://github.com/JuliaPOMDP/MCTS.jl/blob/cbc11a97daf0b095731f7d228bd7cb52c8b7e294/src/dpw.jl
on line 133, there is a ``push!`` to ``tree.transitions`` that happens whether ``spnode`` was seen before or not.

**Comment by zsunberg** [comment]
@rcnlee , thanks for your close scrutiny!

Your understanding seems to be correct. For actions, I think it is correctly handled. For state transitions, it doesn't exactly match the psuedocode for determining when it should be widened. I think we should fix this.

The reason for having transitions be a vector is because it is easy to sample from. Instead of maintaining counts for all the transitions, we simply insert the transitions more than once, and we get constant-time sampling.

I think the fix to make it like the psuedocode is to add an `n_a_children::Vector{Int}` field to the tree type that keeps track of the number of children each action node has. That can be used for the $k N^\alpha$ calculation. If check_repeat_state is true, `tree.n_a_children[sanode]` might be less than `length(tree.transitions[sanode])`. Do you want to take a crack at that?

**Comment by rcnlee** [comment]
Thanks @zsunberg , yes, I'm happy to take a stab at it.

I'm not quite following your description.  I thought what we need is the number of _unique_ children of sanode?  So unique ``(s,a,s')`` tuples need to be tracked.  I don't quite see how unique ``s'`` are being tracked by your method.

How about the following:
1. Create a ``n_a_children::Vector{Int}``.  When presented with a new ``s'``, check it against all existing next states in ``transitions[sanode]`` and if it is unique, increment ``n_a_children[sanode]``.  Use ``n_a_children[sanode]`` in the dpw bound.
1. Create a ``sa_children::Vector{Set{Int}}``.  When presented with a new ``s'``, add it to the set ``push!(sa_children[sanode], s')`` and let the set handle the uniqueness checking.  Then, use ``length(sa_children[sanode])`` in the dpw bound.

The second one might be more efficient.  What do you think?

**Comment by zsunberg** [comment]
I was imagining 1, but, as you point out, that might not be very efficient.

I do not think 2 will be efficient because Set creation has a fairly large overhead, so we don't want to maintain a tiny set for each node. (I have tried implementing MCTS variants with tiny dictionaries in the nodes, and it is usually slow)

I think the best thing to do would be to add both `n_a_children::Vector{Int}` and one big Set, `unique_transitions::Set{Tuple{Int,Int}}` to the tree. Then, when a new `s'` is generated, look up `spnode` with `s_lookup` (or insert it) and check `(sanode, spnode) in unique_transitions` to see if `n_a_children` should be incremented.

**Comment by rcnlee** [comment]
That sounds good.  I'll take a stab and be back with a PR!
