### ISSUE TITLE
State node doesn't contain the state?

### ISSUE THREAD

**Issue by unhandyandy** [JuliaPOMDP/MCTS.jl#45]
Does anyone else find it inconvenient that the state node type has no field for the state?

**Comment by zsunberg** [comment]
Hmmm... yeah, that does seem annoying - it would probably be fine to just add it even though it's not strictly needed for the algorithm.

Actually, performance would probably be significantly improved by upgrading to a vector-based tree structure like in DPW: https://github.com/JuliaPOMDP/MCTS.jl/blob/4c5e9d9400bbf0a070d916d49bf8e46dde80826d/src/dpw_types.jl#L157

**Comment by zsunberg** [comment]
If you want to make a PR to add the state or upgrade the whole tree structure, I'm happy to review it :)

**Comment by unhandyandy** [comment]
I'm not a pro-grade programmer, but my first take is that it would seem more logical to have StateNode contain the state and StateActionNode contain only the action - it now also contains the new state.  That would be more memory efficient, but perhaps slower?

**Comment by zsunberg** [comment]
Performance in Julia is a little bit different than in other languages. Actually what is there right now is pretty slow because in Julia (afaik, at least in v0.6), every mutable object has to be allocated on the heap. So allocating all these state nodes is what is actually bad. I have re-implemented all of our other versions of MCTS (BasicPOMCP, MCTS-DPW, POMCPOW, etc.) with a vector-based tree structure (see link above) and they are much faster. That is what should be done.

**Comment by unhandyandy** [comment]
Sounds good.

**Comment by zsunberg** [comment]
I started working on replacing the tree in the `vector_tree` branch

**Comment by unhandyandy** [comment]
Cool, looking forward to it
