### ISSUE TITLE
Any low-hanging fruit ways to make vanilla MCTS more mem-efficient?

### ISSUE THREAD

**Issue by Shushman** [JuliaPOMDP/MCTS.jl#66]
There might not really be a good answer here; the model I'm working with for a side project is super bulky (part of the state is a graph of 7k vertices and 90k edges), and the `gen` involves simulating the removal of some vertices and then propagating a disease for one timestep.

Even so, I was wondering if anyone had any easy ideas to make the vanilla implementation more memory efficient?

**Comment by zsunberg** [comment]
Hi @Shushman ,

I think that this is best fixed in the problem implementation. The state should only include the minimum amount of information to describe how the environment changes over time. Copying the entire graph isn't necessary for this.

One option is to put the original graph in the MDP object, and let the state be a list of deleted edges and infected nodes.

Another similar option for dealing with very large states is to store a pointer to a snapshot of the full state (the graph in this case), and then in each new state object store the changes since that snapshot. After enough changes have accumulated, you can create a new snapshot and have subsequently generated states point to that. This is similar to keyframes in video compression (https://en.wikipedia.org/wiki/Key_frame - see the Video Compression section). 

Will one of these solutions work?

**Comment by Shushman** [comment]
Thanks Zach! That all makes sense, and I was having a discussion along similar lines with Jayesh as well. I'll start with the first option, and then switch to the keyframe based ones when we are simulating along much longer horizons.
